baseURL = "/"
title = "Shafik"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Mohd. Shafikur Rahman"
googleAnalytics = "XXX"
disqusShortname = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Mohd. Shafikur Rahman"
    profile = "shafik.xyz"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Shafik"
    description = ""
    github = "https://github.com/shafikshaon"
    gitlab = "https://gitlab.com/shafikshaon"
    linkedin = "https://linkedin.com/in/shafikshaon/"
    twitter = "https://twitter.com/shafikshaon"
    stackoverflow = "https://stackoverflow.com/users/4751726/"
    email = "shafikshaon@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[menu]

  [[menu.main]]
      name = "Blog"
      url = "/"
      weight = 1

  [[menu.main]]
      name = "Me"
      url = "/me/"
      weight = 2

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 3

#  [[menu.main]]
#      weight = 1
#      parent = "nav_4"
#      name = "Code of Conduct"
#      identifier = "conduct"
#      url = "/about/conduct/"
#
#  [[menu.main]]
#      weight = 2
#      parent = "nav_4"
#      name = "Sponsors"
#      identifier = "sponsors"
#      url = "/about/sponsors/"
#
#  [[menu.main]]
#      weight = 3
#      parent = "nav_4"
#      name = "Our Team"
#      identifier = "team"
#      url = "/about/team/"